# Data Loading

In [1]:
import pandas as pd

In [4]:
pd.read_csv('RAW_yellow_tlc_apr2022.csv')

    VendorID;tpep_pickup_datetime;tpep_dropoff_datetime;passenger_count;trip_distance;RatecodeID;store_and_fwd_flag;PULocationID;DOLocationID;payment_type;fare_amount;extra;mta_tax;tip_amount;tolls_amount;improvement_surcharge;total_amount;congestion_surcharge;airport_fee
0    2;2022-04-01 0:04:55;2022-04-01 0:14:38;1.0;02...
1    1;2022-04-01 6:02:11;2022-04-01 6:21:36;1.0;5....
2    2;2022-04-01 8:45:59;2022-04-01 9:04:37;1.0;3....
3    2;2022-04-01 9:25:53;2022-04-01 9:30:41;1.0;0....
4    2;2022-04-01 12:30:37;2022-04-01 12:42:09;1.0;...
..                                                 ...
995  2;2022-04-28 18:28:00;2022-04-28 19:11:00;;5.5...
996  2;2022-04-29 9:39:00;2022-04-29 10:06:00;;4.82...
997  1;2022-04-29 15:09:54;2022-04-29 15:13:36;;0.4...
998  2;2022-04-30 6:12:00;2022-04-30 6:27:00;;4.47;...
999  1;2022-04-30 12:20:37;2022-04-30 12:25:41;;0.9...

[1000 rows x 1 columns]

In [7]:
df = pd.read_csv('RAW_yellow_tlc_apr2022.csv',sep=';')
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2022-04-01 0:04:55,2022-04-01 0:14:38,1.0,2.02,1.0,N,114,170,3,9.00,0.50,0.5,0.00,0.0,0.3,12.80,2.5,0.00
1,1,2022-04-01 6:02:11,2022-04-01 6:21:36,1.0,5.70,1.0,N,132,216,3,19.00,1.25,0.5,0.00,0.0,0.3,21.05,0.0,1.25
2,2,2022-04-01 8:45:59,2022-04-01 9:04:37,1.0,3.16,1.0,N,211,162,2,14.50,0.00,0.5,3.56,0.0,0.3,21.36,2.5,0.00
3,2,2022-04-01 9:25:53,2022-04-01 9:30:41,1.0,0.69,1.0,N,237,236,2,5.50,0.00,0.5,0.80,0.0,0.3,9.60,2.5,0.00
4,2,2022-04-01 12:30:37,2022-04-01 12:42:09,1.0,2.20,1.0,N,238,237,2,10.00,0.00,0.5,3.33,0.0,0.3,16.63,2.5,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2,2022-04-28 18:28:00,2022-04-28 19:11:00,NaN,5.55,NaN,NaN,144,239,1,30.03,0.00,0.5,7.39,0.0,0.3,40.72,NaN,NaN
996,2,2022-04-29 9:39:00,2022-04-29 10:06:00,NaN,4.82,NaN,NaN,230,261,1,25.84,0.00,0.5,6.48,0.0,0.3,35.62,NaN,NaN
997,1,2022-04-29 15:09:54,2022-04-29 15:13:36,NaN,0.40,NaN,NaN,236,236,1,4.50,0.00,0.5,1.56,0.0,0.3,9.36,NaN,NaN
998,2,2022-04-30 6:12:00,2022-04-30 6:27:00,NaN,4.47,NaN,NaN,33,4,1,17.51,0.00,0.5,4.64,0.0,0.3,25.45,NaN,NaN
999,1,2022-04-30 12:20:37,2022-04-30 12:25:41,NaN,0.90,NaN,NaN,161,230,1,5.50,0.00,0.5,2.20,0.0,0.3,11.00,NaN,NaN

# How many null values

In [8]:
df.isnull().sum()

VendorID                  0
tpep_pickup_datetime      0
tpep_dropoff_datetime     0
passenger_count          23
trip_distance             0
RatecodeID               23
store_and_fwd_flag       23
PULocationID              0
DOLocationID              0
payment_type              0
fare_amount               0
extra                     0
mta_tax                   0
tip_amount                0
tolls_amount              0
improvement_surcharge     0
total_amount              0
congestion_surcharge     23
airport_fee              23
dtype: int64

In [10]:
#is there any duplicate rows
df.duplicated().sum()

0

so, there is no duplicate rows

In [21]:
#we will remove null values with median
df['airport_fee'] = df['airport_fee'].fillna(df['airport_fee'].median())
df['passenger_count']=df['passenger_count'].fillna(df['passenger_count'].median())
df['congestion_surcharge']=df['congestion_surcharge'].fillna(df['congestion_surcharge'].median())
df['RatecodeID']=df['RatecodeID'].fillna(df['RatecodeID'].median())
#filling with mode store_and_fwd_flag
df['store_and_fwd_flag']= df['store_and_fwd_flag'].fillna(df['store_and_fwd_flag'].mode()[0])
df

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2022-04-01 0:04:55,2022-04-01 0:14:38,1.0,2.02,1.0,N,114,170,3,9.00,0.50,0.5,0.00,0.0,0.3,12.80,2.5,0.00
1,1,2022-04-01 6:02:11,2022-04-01 6:21:36,1.0,5.70,1.0,N,132,216,3,19.00,1.25,0.5,0.00,0.0,0.3,21.05,0.0,1.25
2,2,2022-04-01 8:45:59,2022-04-01 9:04:37,1.0,3.16,1.0,N,211,162,2,14.50,0.00,0.5,3.56,0.0,0.3,21.36,2.5,0.00
3,2,2022-04-01 9:25:53,2022-04-01 9:30:41,1.0,0.69,1.0,N,237,236,2,5.50,0.00,0.5,0.80,0.0,0.3,9.60,2.5,0.00
4,2,2022-04-01 12:30:37,2022-04-01 12:42:09,1.0,2.20,1.0,N,238,237,2,10.00,0.00,0.5,3.33,0.0,0.3,16.63,2.5,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,2,2022-04-28 18:28:00,2022-04-28 19:11:00,1.0,5.55,1.0,N,144,239,1,30.03,0.00,0.5,7.39,0.0,0.3,40.72,2.5,0.00
996,2,2022-04-29 9:39:00,2022-04-29 10:06:00,1.0,4.82,1.0,N,230,261,1,25.84,0.00,0.5,6.48,0.0,0.3,35.62,2.5,0.00
997,1,2022-04-29 15:09:54,2022-04-29 15:13:36,1.0,0.40,1.0,N,236,236,1,4.50,0.00,0.5,1.56,0.0,0.3,9.36,2.5,0.00
998,2,2022-04-30 6:12:00,2022-04-30 6:27:00,1.0,4.47,1.0,N,33,4,1,17.51,0.00,0.5,4.64,0.0,0.3,25.45,2.5,0.00
999,1,2022-04-30 12:20:37,2022-04-30 12:25:41,1.0,0.90,1.0,N,161,230,1,5.50,0.00,0.5,2.20,0.0,0.3,11.00,2.5,0.00

In [22]:
df.isnull().sum()

VendorID                 0
tpep_pickup_datetime     0
tpep_dropoff_datetime    0
passenger_count          0
trip_distance            0
RatecodeID               0
store_and_fwd_flag       0
PULocationID             0
DOLocationID             0
payment_type             0
fare_amount              0
extra                    0
mta_tax                  0
tip_amount               0
tolls_amount             0
improvement_surcharge    0
total_amount             0
congestion_surcharge     0
airport_fee              0
dtype: int64

In [20]:
df.dtypes

VendorID                   int64
tpep_pickup_datetime      object
tpep_dropoff_datetime     object
passenger_count          float64
trip_distance            float64
RatecodeID               float64
store_and_fwd_flag        object
PULocationID               int64
DOLocationID               int64
payment_type               int64
fare_amount              float64
extra                    float64
mta_tax                  float64
tip_amount               float64
tolls_amount             float64
improvement_surcharge    float64
total_amount             float64
congestion_surcharge     float64
airport_fee              float64
dtype: object

# Saving the df into a CSV

In [23]:
df.to_csv('cleaned_data.csv',index=False)

In [26]:
df.store_and_fwd_flag.value_counts()

store_and_fwd_flag
N    994
Y      6
Name: count, dtype: int64